spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/v1/patients/**
        - id: therapist-service
          uri: lb://therapist-service
          predicates:
            - Path=/api/v1/therapists/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**

management:
  endpoints:
    web:
      exposure:
        include: gateway, routes

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7999
